#pragma once
#include "common.hpp"

#include <memory>
#include <optional>
#include <span>
#include <string>
#include <vector>

namespace bb
{

enum class ImageFormat : bb::u8
{
    NONE,

    // Depth
    D16_UNORM,
    D32_SFLOAT,

    // Color sRGB
    // sRGB is not used in the renderer as things are gamma corrected in the pipeline
    R8G8B8A8_SRGB,
    R8G8B8_SRGB,
    R8G8_SRGB,
    R8_SRGB,

    // Linear UNORM
    R8G8B8A8_UNORM,
    B8G8R8A8_UNORM,
    R8G8B8_UNORM,
    R8G8_UNORM,
    R8_UNORM,

    // HDR / floating point
    R32G32B32A32_SFLOAT,
    R16G16B16A16_SFLOAT,
    R16G16_SFLOAT,
    R32_SFLOAT,
};

struct Image2D
{
    static std::optional<Image2D> fromFile(std::string_view path);
    static std::optional<Image2D> fromMemory(std::span<const std::byte> data);

    // TODO: pretty hard to do bounds checking with std::byte[]
    // std::vector is also suboptimal cause we don't need to resize + can't attach custom destructor and can't make from a ptr (what stbi gives us)
    std::shared_ptr<std::byte[]> data {}; // Leave empty to create empty textures
    ImageFormat format {};
    bb::u32 width {};
    bb::u32 height {};
};

struct Cubemap
{
    // No support for providing initial image data: all cubemaps in engine are generated by graphics
    ImageFormat format {};
    bb::u32 width {};
    bb::u32 height {};
};

}

enum class ImageType
{
    e2D,
    eDepth,
    eCubeMap,
    eShadowMap
};