name: PR-Checks

# For more info on the checks enabled see: https://clang.llvm.org/extra/clang-tidy/checks/list.html

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-project:
    name: Build and Test Project

    strategy:
      fail-fast: true
      matrix:
        platform: [ ubuntu-latest, windows-latest ]
        configuration: [ Debug, Distribution ]

    runs-on: ${{ matrix.platform }}

    env:
      OPTION_ARGS: -DWARNINGS_AS_ERRORS=ON -DCOMPILE_SHADERS=OFF -DENABLE_PCH=OFF -DENABLE_UNITY=OFF
      PRESET_PREFIX: ${{ matrix.platform == 'windows-latest' && 'Win64' || matrix.platform == 'ubuntu-latest' && 'WSL' }}
      PRESET_SUFFIX: ${{ matrix.configuration }}

    steps:
      # Check out project

      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      # Install all dependencies

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Setup Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@main
        with:
          vulkan-query-version: latest
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true

      # Configure, Build and Test

      - name: Configure Project
        run: cmake --preset ${{ env.PRESET_PREFIX }}-${{ env.PRESET_SUFFIX }} ${{ env.OPTION_ARGS }}

      - name: Build Project
        run: cmake --build build/${{ env.PRESET_PREFIX }}-${{ env.PRESET_SUFFIX }}

      - name: Test Project
        run: build/${{ env.PRESET_PREFIX }}-${{ env.PRESET_SUFFIX }}/UnitTests
